name: facility
channels:
    - defaults
dependencies:
    - numpy
    - matplotlib
    - pandas
    - pytest
    - scipy
    - seaborn
    - pip
    - jupyter
    - click
    - Sphinx
    - coverage
    - awscli
    - flake8
    - python-dotenv
    - pip:
        - EoN
        - ortools
        - -e .src