name: facility
channels:
    - defaults
dependencies:
    - numpy
    - matplotlib
    - pandas
    - pytest
    - scipy
    - seaborn
    - pip
    - jupyter
    - pip:
          - EoN
          - ortools